import React from 'react'
import DataGrid from '../components/Datagrid'

export default function Teste() {
  const data = [
    {
      solicitante: 'John Doe',
      matricula: 12345,
      epi: 'Óculos de segurança',
      dataSolicitada: new Date(),
      quantidade: '1 unidade',
      imagem: 'caminho/para/imagem.jpg',
      tamanho: 'M',
      status: 'Aprovado',
      acoes: <button>Editar</button>,
    },
    {
      solicitante: 'John Doe',
      matricula: 12345,
      epi: 'Óculos de segurança',
      dataSolicitada: new Date(),
      quantidade: '1 unidade',
      imagem: 'caminho/para/imagem.jpg',
      tamanho: 'M',
      status: 'Aprovado',
      acoes: <button>Editar</button>,
    },
    {
      solicitante: 'John Doe',
      matricula: 12345,
      epi: 'Óculos de segurança',
      dataSolicitada: new Date(),
      quantidade: '1 unidade',
      imagem: 'caminho/para/imagem.jpg',
      tamanho: 'M',
      status: 'Aprovado',
      acoes: <button>Editar</button>,
    },
    {
      solicitante: 'John Doe',
      matricula: 12345,
      epi: 'Óculos de segurança',
      dataSolicitada: new Date(),
      quantidade: '1 unidade',
      imagem: 'caminho/para/imagem.jpg',
      tamanho: 'M',
      status: 'Aprovado',
      acoes: <button>Editar</button>,
    },
    {
      solicitante: 'John Doe',
      matricula: 12345,
      epi: 'Óculos de segurança',
      dataSolicitada: new Date(),
      quantidade: '1 unidade',
      imagem: 'caminho/para/imagem.jpg',
      tamanho: 'M',
      status: 'Aprovado',
      acoes: <button>Editar</button>,
    },
    {
      solicitante: 'John Doe',
      matricula: 12345,
      epi: 'Óculos de segurança',
      dataSolicitada: new Date(),
      quantidade: '1 unidade',
      imagem: 'caminho/para/imagem.jpg',
      tamanho: 'M',
      status: 'Aprovado',
      acoes: <button>Editar</button>,
    },
    {
      solicitante: 'John Doe',
      matricula: 12345,
      epi: 'Óculos de segurança',
      dataSolicitada: new Date(),
      quantidade: '1 unidade',
      imagem: 'caminho/para/imagem.jpg',
      tamanho: 'M',
      status: 'Aprovado',
      acoes: <button>Editar</button>,
    },
    {
      solicitante: 'John Doe',
      matricula: 12345,
      epi: 'Óculos de segurança',
      dataSolicitada: new Date(),
      quantidade: '1 unidade',
      imagem: 'caminho/para/imagem.jpg',
      tamanho: 'M',
      status: 'Aprovado',
      acoes: <button>Editar</button>,
    },
    {
      solicitante: 'John Doe',
      matricula: 12345,
      epi: 'Óculos de segurança',
      dataSolicitada: new Date(),
      quantidade: '1 unidade',
      imagem: 'caminho/para/imagem.jpg',
      tamanho: 'M',
      status: 'Aprovado',
      acoes: <button>Editar</button>,
    },
    {
      solicitante: 'John Doe',
      matricula: 12345,
      epi: 'Óculos de segurança',
      dataSolicitada: new Date(),
      quantidade: '1 unidade',
      imagem: 'caminho/para/imagem.jpg',
      tamanho: 'M',
      status: 'Aprovado',
      acoes: <button>Editar</button>,
    },
    {
      solicitante: 'John Doe',
      matricula: 12345,
      epi: 'Óculos de segurança',
      dataSolicitada: new Date(),
      quantidade: '1 unidade',
      imagem: 'caminho/para/imagem.jpg',
      tamanho: 'M',
      status: 'Aprovado',
      acoes: <button>Editar</button>,
    },
    {
      solicitante: 'John Doe',
      matricula: 12345,
      epi: 'Óculos de segurança',
      dataSolicitada: new Date(),
      quantidade: '1 unidade',
      imagem: 'caminho/para/imagem.jpg',
      tamanho: 'M',
      status: 'Aprovado',
      acoes: <button>Editar</button>,
    },
    {
      solicitante: 'John Doe',
      matricula: 12345,
      epi: 'Óculos de segurança',
      dataSolicitada: new Date(),
      quantidade: '1 unidade',
      imagem: 'caminho/para/imagem.jpg',
      tamanho: 'M',
      status: 'Aprovado',
      acoes: <button>Editar</button>,
    },
    // Adicione mais itens de dados conforme necessário
  ]

  return (
    <div>
      <DataGrid data={data} />
    </div>
  )
}
